=== ku-sldg/rust-am-clients/json_schemas/rodeo_client_response_schema.json
{
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "title": "RodeoClientResponse",
    "description": "Rodeo Client Response structure",
    "type": "object", 
    "properties": {
        "RodeoClientResponse_success": 
            {
                "description": "Boolean flag indicating overall attestation and/or appraisal success",
                "type": "boolean"
            },
        "RodeoClientResponse_error":
            {
                "description": "String indicating errors that occured during attestation",
                "type": "string"
            },
        "RodeoClientResponse_cvm_request":  { "$ref": "cvm_run_message_schema.json#" },
        "RodeoClientResponse_cvm_response": { "$ref": "cvm_run_message_schema.json#" }
    },
    "required": ["RodeoClientResponse_success", "RodeoClientResponse_cvm_request"]
  }

=== ku-sldg/rust-am-clients/json_schemas/tests/rodeo_reqs/test_rodeo_resp.json
{
    "RodeoClientResponse_success": true,
    "RodeoClientResponse_error": "",
    "RodeoClientResponse_cvm_request": {
        "TYPE": "REQUEST",
        "ACTION": "RUN",
        "REQ_PLC": "TOP_PLC",
        "TO_PLC": "P0",
        "TERM": {
            "TERM_CONSTRUCTOR": "lseq",
            "TERM_BODY": [
                {
                    "TERM_CONSTRUCTOR": "bseq",
                    "TERM_BODY": [
                        [
                            "ALL",
                            "ALL"
                        ],
                        {
                            "TERM_CONSTRUCTOR": "asp",
                            "TERM_BODY": {
                                "ASP_CONSTRUCTOR": "ASPC",
                                "ASP_BODY": {
                                    "ASP_ID": "hashdir",
                                    "ASP_ARGS": {
                                        "env_var": "",
                                        "env_var_golden": "",
                                        "filepath_golden": "/Users/adampetz/Documents/Summer_2025/maestro_repos//am-cakeml/tests/DemoFiles/goldenFiles/micro_dir_1_golden.txt",
                                        "omit_file_suffixes": [],
                                        "paths": [
                                            "/Users/adampetz/Documents/Spring_2023//INSPECTA-models/micro-examples/microkit/aadl_port_types/data/base_type/aadl/"
                                        ],
                                        "recursive": false
                                    },
                                    "ASP_PLC": "micro_demo_Plc",
                                    "ASP_TARG_ID": "aadl_dir_targ"
                                }
                            }
                        },
                        {
                            "TERM_CONSTRUCTOR": "asp",
                            "TERM_BODY": {
                                "ASP_CONSTRUCTOR": "ASPC",
                                "ASP_BODY": {
                                    "ASP_ID": "hashdir",
                                    "ASP_ARGS": {
                                        "env_var": "",
                                        "env_var_golden": "",
                                        "filepath_golden": "/Users/adampetz/Documents/Summer_2025/maestro_repos//am-cakeml/tests/DemoFiles/goldenFiles/micro_dir_2_golden.txt",
                                        "omit_file_suffixes": [],
                                        "paths": [
                                            "/Users/adampetz/Documents/Spring_2023//INSPECTA-models/micro-examples/microkit/aadl_port_types/data/base_type/hamr/microkit/"
                                        ],
                                        "recursive": false
                                    },
                                    "ASP_PLC": "micro_demo_Plc",
                                    "ASP_TARG_ID": "microkit_dir_targ"
                                }
                            }
                        }
                    ]
                },
                {
                    "TERM_CONSTRUCTOR": "asp",
                    "TERM_BODY": {
                        "ASP_CONSTRUCTOR": "APPR"
                    }
                }
            ]
        },
        "EVIDENCE": [
            {
                "RawEv": []
            },
            {
                "EvidenceT_CONSTRUCTOR": "mt_evt"
            }
        ],
        "ATTESTATION_SESSION": {
            "Session_Plc": "P0",
            "Plc_Mapping": {
                "P2": "127.0.0.1:5002",
                "P6": "127.0.0.1:5006",
                "P4": "127.0.0.1:5004",
                "P0": "127.0.0.1:5000",
                "P5": "127.0.0.1:5005",
                "P3": "127.0.0.1:5003",
                "P1": "127.0.0.1:5001"
            },
            "PubKey_Mapping": {},
            "Session_Context": {
                "ASP_Types": {
                    "readfile_appr": {
                        "FWD": "REPLACE",
                        "EvInSig": "ALL",
                        "EvOutSig": {
                            "EvOutSig_CONSTRUCTOR": "OutN",
                            "EvOutSig_BODY": 1
                        }
                    },
                    "certificate": {
                        "FWD": "EXTEND",
                        "EvInSig": "ALL",
                        "EvOutSig": {
                            "EvOutSig_CONSTRUCTOR": "OutN",
                            "EvOutSig_BODY": 1
                        }
                    },
                    "sig": {
                        "FWD": "EXTEND",
                        "EvInSig": "ALL",
                        "EvOutSig": {
                            "EvOutSig_CONSTRUCTOR": "OutN",
                            "EvOutSig_BODY": 1
                        }
                    },
                    "readfile": {
                        "FWD": "EXTEND",
                        "EvInSig": "ALL",
                        "EvOutSig": {
                            "EvOutSig_CONSTRUCTOR": "OutN",
                            "EvOutSig_BODY": 1
                        }
                    },
                    "uptime": {
                        "FWD": "EXTEND",
                        "EvInSig": "ALL",
                        "EvOutSig": {
                            "EvOutSig_CONSTRUCTOR": "OutN",
                            "EvOutSig_BODY": 1
                        }
                    },
                    "hashfile": {
                        "FWD": "EXTEND",
                        "EvInSig": "ALL",
                        "EvOutSig": {
                            "EvOutSig_CONSTRUCTOR": "OutN",
                            "EvOutSig_BODY": 1
                        }
                    },
                    "invary_get_measurement": {
                        "FWD": "EXTEND",
                        "EvInSig": "ALL",
                        "EvOutSig": {
                            "EvOutSig_CONSTRUCTOR": "OutN",
                            "EvOutSig_BODY": 1
                        }
                    },
                    "magic_appr": {
                        "FWD": "REPLACE",
                        "EvInSig": "ALL",
                        "EvOutSig": {
                            "EvOutSig_CONSTRUCTOR": "OutN",
                            "EvOutSig_BODY": 1
                        }
                    },
                    "large_output": {
                        "FWD": "EXTEND",
                        "EvInSig": "ALL",
                        "EvOutSig": {
                            "EvOutSig_CONSTRUCTOR": "OutN",
                            "EvOutSig_BODY": 1
                        }
                    },
                    "appraise": {
                        "FWD": "EXTEND",
                        "EvInSig": "ALL",
                        "EvOutSig": {
                            "EvOutSig_CONSTRUCTOR": "OutN",
                            "EvOutSig_BODY": 1
                        }
                    },
                    "sig_tpm_appr": {
                        "FWD": "REPLACE",
                        "EvInSig": "ALL",
                        "EvOutSig": {
                            "EvOutSig_CONSTRUCTOR": "OutN",
                            "EvOutSig_BODY": 1
                        }
                    },
                    "hashdir": {
                        "FWD": "EXTEND",
                        "EvInSig": "ALL",
                        "EvOutSig": {
                            "EvOutSig_CONSTRUCTOR": "OutN",
                            "EvOutSig_BODY": 1
                        }
                    },
                    "sig_appr": {
                        "FWD": "REPLACE",
                        "EvInSig": "ALL",
                        "EvOutSig": {
                            "EvOutSig_CONSTRUCTOR": "OutN",
                            "EvOutSig_BODY": 1
                        }
                    },
                    "sig_tpm": {
                        "FWD": "EXTEND",
                        "EvInSig": "ALL",
                        "EvOutSig": {
                            "EvOutSig_CONSTRUCTOR": "OutN",
                            "EvOutSig_BODY": 1
                        }
                    },
                    "invary_get_measurement_appr": {
                        "FWD": "REPLACE",
                        "EvInSig": "ALL",
                        "EvOutSig": {
                            "EvOutSig_CONSTRUCTOR": "OutN",
                            "EvOutSig_BODY": 1
                        }
                    },
                    "attest": {
                        "FWD": "EXTEND",
                        "EvInSig": "ALL",
                        "EvOutSig": {
                            "EvOutSig_CONSTRUCTOR": "OutN",
                            "EvOutSig_BODY": 1
                        }
                    },
                    "selinux_pol_dump": {
                        "FWD": "EXTEND",
                        "EvInSig": "ALL",
                        "EvOutSig": {
                            "EvOutSig_CONSTRUCTOR": "OutN",
                            "EvOutSig_BODY": 1
                        }
                    },
                    "hashevidence": {
                        "FWD": "EXTEND",
                        "EvInSig": "ALL",
                        "EvOutSig": {
                            "EvOutSig_CONSTRUCTOR": "OutN",
                            "EvOutSig_BODY": 1
                        }
                    },
                    "hashfile_appr": {
                        "FWD": "REPLACE",
                        "EvInSig": "ALL",
                        "EvOutSig": {
                            "EvOutSig_CONSTRUCTOR": "OutN",
                            "EvOutSig_BODY": 1
                        }
                    },
